1. Understand the Problem
          ↓
2. Load and Explore Data
          ↓
3. Data Cleaning
          ↓
4. Exploratory Data Analysis (EDA)
          ↓
5. Feature Engineering
          ↓
6. Data Preprocessing
          ↓
7. Split Data
          ↓
8. Train Baseline Model
          ↓
9. Train Multiple Algorithms
          ↓
10. Hyperparameter Tuning
          ↓
11. Evaluate Models
          ↓
12. Interpret Results
          ↓
13. Save Best Model
          ↓
14. Deployment (Optional)

In [83]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [84]:
# Load the Dataset
df = pd.read_csv("AmesHousing.csv")

In [85]:
# Data Cleaning Handling missing values
df.head()

,Order,PID,MS SubClass,MS Zoning,Lot Frontage,Lot Area,Street,Alley,Lot Shape,Land Contour,...,Pool Area,Pool QC,Fence,Misc Feature,Misc Val,Mo Sold,Yr Sold,Sale Type,Sale Condition,SalePrice
0,1,526301100,20,RL,141.0,31770,Pave,NaN,IR1,Lvl,...,0,NaN,NaN,NaN,0,5,2010,WD,Normal,215000
1,2,526350040,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,...,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal,105000
2,3,526351010,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,...,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal,172000
3,4,526353030,20,RL,93.0,11160,Pave,NaN,Reg,Lvl,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,244000
4,5,527105010,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,...,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal,189900

In [86]:
# Order and PID are irrelevant column in this dataset.
df = df.drop(columns=['Order', 'PID'])
df.head()

,MS SubClass,MS Zoning,Lot Frontage,Lot Area,Street,Alley,Lot Shape,Land Contour,Utilities,Lot Config,...,Pool Area,Pool QC,Fence,Misc Feature,Misc Val,Mo Sold,Yr Sold,Sale Type,Sale Condition,SalePrice
0,20,RL,141.0,31770,Pave,NaN,IR1,Lvl,AllPub,Corner,...,0,NaN,NaN,NaN,0,5,2010,WD,Normal,215000
1,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,AllPub,Inside,...,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal,105000
2,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,AllPub,Corner,...,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal,172000
3,20,RL,93.0,11160,Pave,NaN,Reg,Lvl,AllPub,Corner,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,244000
4,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,AllPub,Inside,...,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal,189900

In [87]:
# Nominal Columns handling missing values.
# Extracting Nominal columns
numerical_columns = df.select_dtypes(include=['number'])
numerical_columns

,MS SubClass,Lot Frontage,Lot Area,Overall Qual,Overall Cond,Year Built,Year Remod/Add,Mas Vnr Area,BsmtFin SF 1,BsmtFin SF 2,...,Wood Deck SF,Open Porch SF,Enclosed Porch,3Ssn Porch,Screen Porch,Pool Area,Misc Val,Mo Sold,Yr Sold,SalePrice
0,20,141.0,31770,6,5,1960,1960,112.0,639.0,0.0,...,210,62,0,0,0,0,0,5,2010,215000
1,20,80.0,11622,5,6,1961,1961,0.0,468.0,144.0,...,140,0,0,0,120,0,0,6,2010,105000
2,20,81.0,14267,6,6,1958,1958,108.0,923.0,0.0,...,393,36,0,0,0,0,12500,6,2010,172000
3,20,93.0,11160,7,5,1968,1968,0.0,1065.0,0.0,...,0,0,0,0,0,0,0,4,2010,244000
4,60,74.0,13830,5,5,1997,1998,0.0,791.0,0.0,...,212,34,0,0,0,0,0,3,2010,189900
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2925,80,37.0,7937,6,6,1984,1984,0.0,819.0,0.0,...,120,0,0,0,0,0,0,3,2006,142500
2926,20,NaN,8885,5,5,1983,1983,0.0,301.0,324.0,...,164,0,0,0,0,0,0,6,2006,131000
2927,85,62.0,10441,5,5,1992,1992,0.0,337.0,0.0,...,80,32,0,0,0,0,700,7,2006,132000
2928,20,77.0,10010,5,5,1974,1975,0.0,1071.0,123.0,...,240,38,0,0,0,0,0,4,2006,170000
2929,60,74.0,9627,7,5,1993,1994,94.0,758.0,0.0,...,190,48,0,0,0,0,0,11,2006,188000

- Lot frontage has 490 missing values filled the missing values with Neighborhood Lot Frontage Median. After the filling the new missing values are 3. Moreover, I sepculated that maybe lot area could dervie the lot frontage but that intuition wasn't justified by mathematics.\

- Lot Area has no missing values\

- Overall Qual and Overall Cond do not have any missing values.\

- Year built and Year Remod/Add do not have any missing values. Feature Engineering can be done here.\

- Mas Vnr Area has 23 Missing Values.\

- Garage Yr Blt has 159 Missing Values. But it is not missing at random rather garage do not exist.

-

In [88]:
numerical_columns['Lot Frontage'] = (
    df.groupby('Neighborhood')['Lot Frontage']
      .transform(lambda x: x.fillna(x.median()))
)

Lot Frontage        3
Mas Vnr Area       23
BsmtFin SF 1        1
BsmtFin SF 2        1
Bsmt Unf SF         1
Total Bsmt SF       1
Bsmt Full Bath      2
Bsmt Half Bath      2
Garage Yr Blt     159
Garage Cars         1
Garage Area         1
dtype: int64

**Transformations:**
Mathematical Transformation:
- Lot Frontage have skewness of 1.500 It requires Box-cox or Yeo-Johnson Transformation
- 
---
One Hot Encoding for Nominal Values:
- MS Subclass will undergo One-Hot encoding due to the fact that the feature is not a quantitative measures rather labels.\